'use client';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutComponent from "./components/layout/layout";
import { AuthProvider } from "./context/authContext";
 
import { useContext, useEffect } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  // const checkAuth = async () => {
  //   //checar se o token eh valido    
  //   console.log("check token");
  //   const response = await (await fetch("/api/auth/checkToken")).json();
  //   // const teste = await response.json();
  //   console.log(response);
  //   // console.log(teste);
  // };

 
  // useEffect(() => {
  //   checkAuth();  
  //   const interval = setInterval(checkAuth, 5000);  

  //   return () => clearInterval(interval);  
  // }, []);
  return (

    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <LayoutComponent>
            {children}
          </LayoutComponent>
        </AuthProvider>
      </body>
    </html>

  );
}
